new: DataLoafPackageDirFmt
qiime2/q2-stats pull request #4
Opened 2022-08-04 19:20 UTC by lizgehret

2022-08-10 19:39 UTC, lizgehret commented
Pending successful CI this is ready for review @ebolyen 🚀

2022-09-29 21:08 UTC, ebolyen requested changes

2022-09-29 21:08 UTC, ebolyen commented on q2_stats/_format.py
> +    data_slices = model.FileCollection(r'.+\.csv', format=NDJSONFileFormat)
We should pick a different format name here since it's CSV.

Maybe `TabularDataCSV` implying there is a Table Schema to be found in a Tabular Data Resource?

2022-09-29 21:08 UTC, ebolyen commented on q2_stats/_format.py
> +    def _check_nutrition_facts(self):
Dead code, should delete

2022-09-29 21:08 UTC, ebolyen commented on q2_stats/_format.py
> +    def _check_matching_data_slices(self):
Dead code

2022-09-29 21:08 UTC, ebolyen commented on q2_stats/_format.py
> +        # self._check_nutrition_facts()
delete

2022-09-29 22:17 UTC, lizgehret commented on q2_stats/_format.py
> +    data_slices = model.FileCollection(r'.+\.csv', format=NDJSONFileFormat)
Sounds good @ebolyen! I ended up going with FrictionlessCSVFileFormat since we're using the frictionless framework.

2022-09-30 17:12 UTC, ebolyen approved these changes

2022-09-30 17:26 UTC, merged